export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as ServicesPage } from './ServicesPage'
export { default as SolutionsPage } from './SolutionsPage'
export { default as CareersPage } from './CareersPage'
export { default as ContactPage } from './ContactPage'
export { default as GalleryPage } from './GalleryPage'
export { default as NotFoundPage } from './NotFoundPage'
